
// Next
import type { NextPage } from "next";
import { useRouter } from "next/router";

import { useQuery } from "@apollo/client"

// Components
import BetPageLayout from "components/layouts/BetPageLayout"

import Head from "next/head";
// Utils
import { extractVfIdFromURL, toHexForGraphProtocol } from "utils/helpers";
import BetPage from "components/betPage";
import { VIRTUAL_FLOORS } from "../../graphql/queries";

const Bet: NextPage = () => {
  const router = useRouter();

  const id = router.asPath.includes("#!")
    ? extractVfIdFromURL(router.asPath, 3)
    : null;
    
  const { data, error } = useQuery(VIRTUAL_FLOORS, {
    variables: {
      vfId: id,
    },
    pollInterval: 1000,
  });

  const vf = data && data.virtualFloor;  

  return (
    <>
      <Head>
        <title>Bet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
      </Head>
      {vf && (
        <BetPageLayout vf={vf}>
          <BetPage vf={vf} />
        </BetPageLayout>
      )}
    </>
  );
};

export default Bet;