// Next
import type { NextPage } from "next";

// Components
import Head from "next/head";
import BetListLayout from "components/layouts/BetListLayout";
import BetsPlacedPage from "components/betsPlacedPage";

const BetsPlaced: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bets Placed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
      </Head>
      <BetListLayout>
        {
          // @ts-ignore
          <BetsPlacedPage />
        }
      </BetListLayout>
    </>
  );
};

export default BetsPlaced;
