import { useEffect } from "react";

// Next
import type { NextPage } from "next";
import Head from "next/head";

// Components
import CreateBet from "components/createBetPage";
import CreateBetPageLayout from "components/layouts/CreateBetPageLayout"

// Redux
import { useDispatch } from "react-redux";
import { removeStepsData } from "components/createBetPage/ducks";

const CreateBetPage: NextPage = () => {
  const dispatch = useDispatch();

  useEffect(() => {
    return () => {
      dispatch(removeStepsData());
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Bet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
      </Head>
      <CreateBetPageLayout>
        <CreateBet />
      </CreateBetPageLayout>
    </>
  );
};

export default CreateBetPage;
