// @ts-nocheck
// Above is for until when the data given here is not coming from backend
// Next
import Head from "next/head";
import type { NextPage } from "next";
import Honeybadger from "@honeybadger-io/js";

// Components
import BetListLayout from "components/layouts/BetListLayout";
import BetList from "components/betList";

const LobbyPage = (): NextPage => {
  return (
    <>
      <Head>
        <title>Lobby</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
      </Head>
      <BetListLayout>
        {
          // @ts-ignore
          <BetList />
        }
      </BetListLayout>
    </>
  );
};

export default LobbyPage;
