// Next
import type { NextPage } from "next";
import Head from "next/head";

// Components
import BetListLayout from "components/layouts/BetListLayout";
import OwnedBetsPage from "components/ownedBetsPage";

const OwnedBets: NextPage = () => {
  return (
    <>
      <Head>
        <title>Owned Bets</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
      </Head>
      <BetListLayout>
        {
          // @ts-ignore
          <OwnedBetsPage />
        }
      </BetListLayout>
    </>
  );
};

export default OwnedBets;
