// Next
import { useRouter } from "next/router";
import Head from "next/head";

// Components
import CreateBetSuccess from "components/successPage";
import { ReactElement } from "react";
import { extractVfIdFromURL } from "utils/helpers";
import FullLayout from "components/layouts/fullLayOut";


const CreateBetSuccessPage = (): ReactElement => {
  const router = useRouter();

  const id = router.asPath.includes("#!")
    ? extractVfIdFromURL(router.asPath, 3)
    : null;

  return (
      <>
        <Head>
          <title>Success</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
        </Head>
        <main>
          <CreateBetSuccess id={id} />
        </main>
      </>
  );
};

export default CreateBetSuccessPage;
